### ISSUE TITLE
How to handle nf run child process options

### ISSUE THREAD

**Issue by bertBruynooghe** [strongloop/node-foreman#154]
In:
```nf run testcafe \"chrome:headless\" ./*.js --screenshots ./```

`--screenshots` is considered as an option of `nf` iso. `testcafe`.

I believe the original foreman fixes this by only considering options directly following the `run` parameter.

**Comment by rmg** [comment]
Use `--` to tell the option parser to stop parsing options/flags:

```
nf run -- testcafe chrome:headless ./*.js --screenshots ./
```

This tells the option parser in `nf` to stop parsing options at `--` and treat everything after it as standard positional arguments (aka, unprocessed strings).

I was curious how `foreman` supported this, since what you described is somewhat non-standard behaviour for a CLI program, so I just took a look. The [Thor](http://whatisthor.com/) gem it uses for CLI parsing has a [`#stop_on_unknown_option!`](https://www.rubydoc.info/github/wycats/thor/Thor/Base/ClassMethods#stop_on_unknown_option%3F-instance_method) method in the API that does pretty much what it says.

_...1 hour** of internet archeology later_

Fun fact: the `--` convention (per `getopt(1)` and `getopt(3)`) for stopping parsing CLI args was first documented in the [AT&T System V Users Manual](http://bitsavers.trailing-edge.com/pdf/att/3b1/999-801-312IS_ATT_UNIX_PC_System_V_Users_Manual_Volume_1.pdf) from 1983 😮 

---

** ok, it was more like 3 hours, and was very entertaining 😊

**Comment by bertBruynooghe** [comment]
👍
